
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuxinyu199795/SpringCloud_config-repo.git
          username: 347151535@qq.com
          password: Lxy199795
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"

